#!/usr/bin/env python3
"""
Agent Prime — Dashboard Generator

Reads shared/registry.json and generates:
  1. prime/dashboard.md (pipeline view + staleness + next action)
  2. projects/README.md (master project index)

Run: python meta/scripts/generate_dashboard.py
"""

import json
import os
from datetime import datetime, timedelta
from pathlib import Path

# Resolve paths relative to Agent Prime root
SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent.parent
REGISTRY_PATH = ROOT / "shared" / "registry.json"
DASHBOARD_PATH = ROOT / "prime" / "dashboard.md"
PROJECTS_INDEX_PATH = ROOT / "projects" / "README.md"


def load_registry():
    with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def days_since(date_str):
    if not date_str:
        return None
    try:
        d = datetime.strptime(date_str, "%Y-%m-%d")
        return (datetime.now() - d).days
    except ValueError:
        return None


def staleness_flag(days):
    if days is None:
        return ""
    if days >= 14:
        return "🔴"
    if days >= 7:
        return "🟡"
    return "✅"


def is_overdue(item):
    if not item.get("due"):
        return False
    try:
        due = datetime.strptime(item["due"], "%Y-%m-%d")
        return datetime.now() > due and item["status"] not in ("done", "published", "parked")
    except ValueError:
        return False


def generate_dashboard(registry):
    items = registry["items"]
    today = datetime.now().strftime("%Y-%m-%d")

    # Categorize
    projects = [i for i in items if i["type"] != "TSK"]
    tasks = [i for i in items if i["type"] == "TSK"]
    active_projects = [p for p in projects if p["status"] in ("in_progress", "planning", "review")]
    active_tasks = [t for t in tasks if t["status"] not in ("done", "published", "parked")]

    # Find top priority
    priority_order = {"P0": 0, "P1": 1, "P2": 2}
    active_all = [i for i in items if i["status"] in ("in_progress", "backlog", "planning", "review", "blocked")]
    active_all.sort(key=lambda x: (priority_order.get(x.get("priority", "P2"), 2), x.get("due") or "9999"))
    top_priority = active_all[0] if active_all else None

    # User owes
    user_tasks = [t for t in active_tasks if t["owner"] == "user"]
    user_overdue = [t for t in user_tasks if is_overdue(t)]

    # Stale items (not updated in 7+ days)
    stale_items = []
    for i in items:
        if i["status"] in ("done", "published", "parked"):
            continue
        days = days_since(i.get("updated"))
        if days and days >= 7:
            stale_items.append((i, days))

    lines = []
    lines.append("# Pipeline Dashboard")
    lines.append("")
    lines.append("> **Auto-generated** from `shared/registry.json`.")
    lines.append(f"> **Generated:** {today}")
    lines.append("> **Do not edit this file manually.** Edit the registry, then regenerate.")
    lines.append("> **Run:** `python meta/scripts/generate_dashboard.py`")
    lines.append("")
    lines.append("---")
    lines.append("")

    # System Pulse
    lines.append(f"## 📊 System Pulse [{today}]")
    lines.append("")
    if top_priority:
        lines.append(f"🎯 **Top priority:** [{top_priority['id']}] {top_priority['title']}")
        if top_priority.get("next_action"):
            lines.append(f"   → {top_priority['next_action']}")
    lines.append(f"⏳ **Stale:** {len(stale_items)} item(s) not updated in 7+ days")
    lines.append(f"📋 **User owes:** {len(user_tasks)} task(s) ({len(user_overdue)} overdue)")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Pipeline Tracker (projects only)
    lines.append("## Pipeline Tracker")
    lines.append("")
    lines.append("| ID | Title | Type | Status | Priority | Next Action |")
    lines.append("|----|-------|------|--------|----------|-------------|")
    for p in sorted(projects, key=lambda x: (priority_order.get(x.get("priority", "P2"), 2), x["id"])):
        status_icon = {"in_progress": "🔵", "planning": "📐", "review": "👀", "published": "✅", "done": "✅", "backlog": "⬜", "blocked": "🚫", "parked": "💤"}.get(p["status"], "")
        next_act = p.get("next_action") or "—"
        lines.append(f"| {p['id']} | {p['title']} | {p['type']} | {status_icon} {p['status']} | {p.get('priority', '—')} | {next_act} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Task Queue (active tasks, sorted by priority)
    lines.append("## Task Queue")
    lines.append("")
    lines.append("| ID | Task | Owner | Priority | Due | Status | Blocked On |")
    lines.append("|----|------|-------|----------|-----|--------|------------|")
    for t in sorted(active_tasks, key=lambda x: (priority_order.get(x.get("priority", "P2"), 2), x.get("due") or "9999")):
        due = t.get("due") or "—"
        overdue_flag = " ⚠️" if is_overdue(t) else ""
        blocked = t.get("blocked_on") or "—"
        lines.append(f"| {t['id']} | {t['title']} | {t['owner']} | {t.get('priority', '—')} | {due}{overdue_flag} | {t['status']} | {blocked} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Staleness Report
    lines.append("## Staleness Report")
    lines.append("")
    if stale_items:
        lines.append("| ID | Title | Days Since Update | Flag |")
        lines.append("|----|-------|-------------------|------|")
        for item, days in sorted(stale_items, key=lambda x: -x[1]):
            lines.append(f"| {item['id']} | {item['title']} | {days} | {staleness_flag(days)} |")
    else:
        lines.append("All items up to date. ✅")
    lines.append("")
    lines.append("---")
    lines.append("")

    # User's Plate
    lines.append("## User's Plate")
    lines.append("")
    if user_tasks:
        lines.append("| ID | Task | Priority | Due | Overdue? |")
        lines.append("|----|------|----------|-----|----------|")
        for t in sorted(user_tasks, key=lambda x: (priority_order.get(x.get("priority", "P2"), 2), x.get("due") or "9999")):
            due = t.get("due") or "—"
            overdue = "⚠️ YES" if is_overdue(t) else "—"
            lines.append(f"| {t['id']} | {t['title']} | {t.get('priority', '—')} | {due} | {overdue} |")
    else:
        lines.append("Nothing assigned to user. 🎉")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*Auto-generated from registry.json on {today}*")

    return "\n".join(lines)


def generate_projects_index(registry):
    items = registry["items"]
    projects = [i for i in items if i["type"] != "TSK"]
    today = datetime.now().strftime("%Y-%m-%d")

    type_names = registry.get("type_definitions", {})
    type_order = ["THS", "EVT", "PRG", "STR", "TLK", "BLD", "SYS", "EXP"]

    lines = []
    lines.append("# Projects — Master Index")
    lines.append("")
    lines.append("> **Auto-generated** from `shared/registry.json`.")
    lines.append(f"> **Generated:** {today}")
    lines.append("> **Do not edit this file manually.** Edit the registry, then regenerate.")
    lines.append("> **Run:** `python meta/scripts/generate_dashboard.py`")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Type legend
    lines.append("## Project Types")
    lines.append("")
    lines.append("| Prefix | Type | Description |")
    lines.append("|--------|------|-------------|")
    for t in type_order:
        desc = type_names.get(t, "")
        lines.append(f"| `{t}` | {t} | {desc} |")
    lines.append("")
    lines.append("## Project States")
    lines.append("")
    lines.append("`backlog` → `planning` → `in_progress` → `review` → `done` / `published` → `parked`")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Group by type
    for ptype in type_order:
        typed = [p for p in projects if p["type"] == ptype]
        if not typed:
            continue

        type_label = type_names.get(ptype, ptype)
        lines.append(f"### {ptype} — {type_label}")
        lines.append("")
        lines.append("| ID | Title | State | Priority | Key Artifact |")
        lines.append("|----|-------|-------|----------|-------------|")
        for p in sorted(typed, key=lambda x: x["id"]):
            folder_name = f"{p['id']}_{p['title'].lower().replace(' ', '_').replace('—', '').replace(':', '').replace('/', '_')[:30]}"
            artifact = "—"
            if p.get("artifacts"):
                artifact = p["artifacts"][0].get("name", "—")
            lines.append(f"| [{p['id']}]({p['id']}_*/) | {p['title']} | {p['status']} | {p.get('priority', '—')} | {artifact} |")
        lines.append("")

    # Counts
    from collections import Counter
    status_counts = Counter(p["status"] for p in projects)
    lines.append("---")
    lines.append("")
    lines.append("## Counts")
    lines.append("")
    lines.append("| State | Count |")
    lines.append("|-------|-------|")
    for status in ["published", "done", "in_progress", "planning", "review", "backlog", "blocked", "parked"]:
        if status_counts.get(status, 0) > 0:
            lines.append(f"| {status} | {status_counts[status]} |")
    lines.append(f"| **Total** | **{len(projects)}** |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*Auto-generated from registry.json on {today}*")

    return "\n".join(lines)


def main():
    if not REGISTRY_PATH.exists():
        print(f"❌ Registry not found at {REGISTRY_PATH}")
        return

    registry = load_registry()
    print(f"📖 Loaded registry: {len(registry['items'])} items")

    # Generate dashboard
    dashboard = generate_dashboard(registry)
    DASHBOARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(DASHBOARD_PATH, "w", encoding="utf-8") as f:
        f.write(dashboard)
    print(f"✅ Dashboard written to {DASHBOARD_PATH}")

    # Generate projects index
    projects_index = generate_projects_index(registry)
    PROJECTS_INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(PROJECTS_INDEX_PATH, "w", encoding="utf-8") as f:
        f.write(projects_index)
    print(f"✅ Projects index written to {PROJECTS_INDEX_PATH}")

    # Print pulse
    items = registry["items"]
    active = [i for i in items if i["status"] not in ("done", "published", "parked")]
    user_tasks = [i for i in active if i["owner"] == "user" and i["type"] == "TSK"]
    overdue = [i for i in user_tasks if is_overdue(i)]
    stale = [i for i in active if days_since(i.get("updated")) and days_since(i["updated"]) >= 7]

    print("")
    print(f"📊 System Pulse [{datetime.now().strftime('%Y-%m-%d')}]")
    p0 = [i for i in active if i.get("priority") == "P0"]
    if p0:
        print(f"🎯 Top priority: [{p0[0]['id']}] {p0[0]['title']}")
    print(f"⏳ Stale: {len(stale)} item(s)")
    print(f"📋 User owes: {len(user_tasks)} task(s) ({len(overdue)} overdue)")


if __name__ == "__main__":
    main()
